version: "3.8"
services:
    backend:
        build: ./backend
        ports:
            - "8080:8080"

    frontend:
        build:
            context: ./frontend
            args:
                - NEXT_PUBLIC_API_URL=http://backend:8080/api
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://backend:8080/api
